### ISSUE TITLE
Tool installation

### ISSUE THREAD

**Issue by klinga** [BookOps-CAT/RL-shelf-ready-validation#28]
I suggest to add another method to install the tool. The package can be pip installed, instead of cloned and run using Poetry (although Poetry will handle creation of the virtual environment).

Something like this:
1. create a directory: `$ mkdir rl-validator`
2. cd to the folder: `$ cd rl-validator`
3. create virtual environment and activate it: `$ python -m venv .venv` & `$ source ./.venv/scripts/activate`
5. finally, install from Github:
`$ pip install git+https://github.com/BookOps-CAT/RL-shelf-ready-validation`

**Comment by charlottekostelic** [comment]
Added with #30
