### ISSUE TITLE
EVIS > EVP

### ISSUE THREAD

**Issue by klinga** [BookOps-CAT/RL-shelf-ready-validation#9]
https://github.com/BookOps-CAT/RL-shelf-ready-validation/blob/a10de35fdc5017b6349e69efac6de81212ae5c32/rl_sr_validation/models.py#L54

There was some confusion with EV at the start of their shelf-ready program. The correct code we all agreed on is "EVP" across bib/order/item data.

**Comment by charlottekostelic** [comment]
Fixed with #15
